export const GET_ALL_DRIVERS = "GET_ALL_DRIVERS";
export const GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID";
export const GET_DRIVERS_BY_NAME = "GET_DRIVERS_BY_NAME";
export const CREATE_DRIVER = "CREATE_DRIVER";
export const DELETE_DRIVER = "DELETE_DRIVER";

export const FETCH_ERROR = "FETCH_ERROR";
